// AUTO-GENERATED by scripts/generate-profile-avatar-data.mjs — do not edit manually.
// Sources: HeadPicData_C (1).txt, ItemData_C (1).txt

export type ProfileAvatarDataRow = {
  /** HeadPicData.ID */
  headPicId: number;
  /** ItemData.ID (wire AvatarID) */
  itemId: number;
  /** 1 = male, 2 = female */
  gender: number;
  /** HeadPicData.Order — display sort */
  order: number;
  /** ItemData.Icon e.g. head_15 — avatar image file stem */
  icon: string;
};

export const PROFILE_AVATAR_ROWS: readonly ProfileAvatarDataRow[] = [
  { headPicId: 1, itemId: 401, gender: 1, order: 1, icon: "head_1" },
  { headPicId: 2, itemId: 406, gender: 2, order: 2, icon: "head_2" },
  { headPicId: 15, itemId: 490, gender: 2, order: 3, icon: "head_15" },
  { headPicId: 16, itemId: 491, gender: 2, order: 4, icon: "head_16" },
  { headPicId: 3, itemId: 414, gender: 1, order: 5, icon: "head_3" },
  { headPicId: 18, itemId: 494, gender: 1, order: 6, icon: "head_19" },
  { headPicId: 20, itemId: 496, gender: 1, order: 7, icon: "head_21" },
  { headPicId: 19, itemId: 495, gender: 2, order: 8, icon: "head_20" },
  { headPicId: 17, itemId: 492, gender: 2, order: 9, icon: "head_17" },
  { headPicId: 5, itemId: 438, gender: 1, order: 10, icon: "head_5" },
  { headPicId: 8, itemId: 448, gender: 1, order: 11, icon: "head_8" },
  { headPicId: 12, itemId: 487, gender: 1, order: 12, icon: "head_12" },
  { headPicId: 6, itemId: 441, gender: 2, order: 13, icon: "head_6" },
  { headPicId: 10, itemId: 485, gender: 1, order: 14, icon: "head_10" },
  { headPicId: 11, itemId: 486, gender: 2, order: 15, icon: "head_11" },
  { headPicId: 13, itemId: 488, gender: 2, order: 16, icon: "head_13" },
  { headPicId: 14, itemId: 489, gender: 2, order: 17, icon: "head_14" },
  { headPicId: 7, itemId: 446, gender: 2, order: 18, icon: "head_7" },
  { headPicId: 4, itemId: 419, gender: 2, order: 19, icon: "head_4" },
  { headPicId: 9, itemId: 455, gender: 2, order: 20, icon: "head_9" },
  { headPicId: 21, itemId: 497, gender: 1, order: 21, icon: "head_22" },
  { headPicId: 23, itemId: 499, gender: 2, order: 23, icon: "head_24" },
];

/** All ItemData Type 5 head icons (includes ids outside HeadPicData). */
export const HEAD_ITEM_ICON_BY_ID: Readonly<Record<number, string>> = {
  401: "head_1",
  406: "head_2",
  414: "head_3",
  419: "head_4",
  438: "head_5",
  441: "head_6",
  446: "head_7",
  448: "head_8",
  455: "head_9",
  485: "head_10",
  486: "head_11",
  487: "head_12",
  488: "head_13",
  489: "head_14",
  490: "head_15",
  491: "head_16",
  492: "head_17",
  493: "head_18",
  494: "head_19",
  495: "head_20",
  496: "head_21",
  497: "head_22",
  498: "head_23",
  499: "head_24",
};
