import type { LegalBlock, LegalSection } from './legalContentTypes'

export const INVITE_FRIENDS_TERMS_TITLE = 'LUKLOK CASINO INVITE FRIENDS TERMS OF USE'
export const INVITE_FRIENDS_TERMS_EFFECTIVE = 'Last Revised: [EFFECTIVE DATE]'

export const INVITE_FRIENDS_TERMS_INTRO: LegalBlock[] = [
  {
    type: 'paragraph',
    text: 'LukLok Casino\'s Invite Friends Program (Invite Friends Program) enables our valued customers to receive rewards when they refer other eligible players to LukLok Casino.',
  },
  {
    type: 'paragraph',
    text: 'These Terms of Use govern your participation in the LukLok Casino Invite Friends Program, including how you can market and promote the Invite Friends Program. In addition to these Terms of Use, participation in the Invite Friends Program is also governed by the LukLok Casino Terms of Service, including our Sweepstakes Policy, Privacy Policy and Responsible Social Play Policy referenced therein.',
  },
  {
    type: 'subheading',
    text: 'Acceptance of Invite Friends Terms of Use and Modifications',
  },
  {
    type: 'paragraph',
    text: 'Each time that you ("you" or "your") invite a friend to LukLok Casino, you confirm that you accept and agree to be bound by these Terms of Use. We may amend these Terms of Use at any time in our sole discretion. Each time that you invite a friend to LukLok Casino, a new binding agreement is formed between you and us. This means that each time you invite a friend to LukLok Casino, you should read these Terms of Use carefully. You will be bound by such amended Terms of Use after the changes are posted here. Thereafter, your continued participation in the Invite Friends Program is deemed to confirm your acceptance of any amendments to these Terms of Use. If you do not agree to any amendments made to these Terms of Use, then you must immediately cease any further participation in the Invite Friends Program.',
  },
  {
    type: 'paragraph',
    text: 'By participating in the Invite Friends Program, you confirm that you have read, accept, and agree to be bound by these Terms of Use.',
  },
  {
    type: 'paragraph',
    text: 'We reserve the right to modify, suspend and/or cancel the Invite Friends Program and/or any associated promotion at any time for any reason in our sole discretion, without notice to you. Words capitalized in these Terms of Use have the meanings given in the LukLok Casino Terms of Service or in the definitions section at the end of these Terms of Use. Words capitalized and in parenthesis in these Terms of Use have the meanings given there.',
  },
  {
    type: 'paragraph',
    text: 'To the extent of any inconsistency between these Terms of Use and any Additional Terms provided by us to you specific to your participation in the Invite Friends Program, the Additional Terms shall prevail.',
  },
]

export const INVITE_FRIENDS_TERMS_SECTIONS: LegalSection[] = [
  {
    id: 'eligibility',
    title: '1. Eligibility',
    blocks: [
      {
        type: 'paragraph',
        text: '1. In order to be eligible to receive Rewards, you must:',
      },
      {
        type: 'list',
        items: [
          'have an active User Account on LukLok Casino that is not suspended or an Unused Account; and',
          'not be voluntarily or involuntarily excluded from play on LukLok Casino;',
        ],
      },
      {
        type: 'paragraph',
        text: '2. You must comply with these Terms of Use and any additional terms that we may supply to you that apply to your participation in the Invite Friends Program.',
      },
      {
        type: 'paragraph',
        text: '3. If we determine in our sole discretion that you are ineligible to play on LukLok Casino, any Rewards that have been awarded to you are immediately forfeited and cancelled.',
      },
    ],
  },
  {
    id: 'invitation-options',
    title: '2. Invitation Options',
    blocks: [
      {
        type: 'paragraph',
        text: '1. In order for an individual to become an Invited Friend, the individual must first click a Link. An individual that clicks your Link will only be deemed an Invited Friend in the event that the individual successfully creates a LukLok Casino User Account after clicking on your Link and successfully completes the Required Activity. All Links, Required Activity and Rewards are available and detailed on the Invite Friends Program Page. In the event a person signs up without using a Link, that person is not an Invited Friend, and you will not be entitled to a Reward.',
      },
      {
        type: 'paragraph',
        text: '2. LukLok Casino reserves the right to reject or cancel the registration of any person that clicks a Link for any reason or no reason, in its sole discretion. LukLok Casino will use reasonable endeavours to track the number of Invited Friends generated by your Links; however, LukLok Casino shall not be responsible for and you shall not be entitled to any Rewards for any Invited Friends generated through fraudulent, misleading, or inaccurate referrals or any referred person who clicks your Link but cannot be tracked by LukLok Casino for any reason.',
      },
      {
        type: 'paragraph',
        text: '3. A person will not be considered an Invited Friend in the event the person clicking your Link cannot be tracked by LukLok Casino. You acknowledge and accept that other Players use Links and that prior to clicking on your Link, a referred person may have clicked the Link of another Player, and that you shall only receive the applicable Reward for the Invited Friend in the event the Invited Friend successfully creates their LukLok Casino Account through your Link.',
      },
      {
        type: 'paragraph',
        text: '4. LukLok Casino records with respect to who is an Invited Friend and who gets the Reward for that Invited Friend shall be final and binding.',
      },
      {
        type: 'paragraph',
        text: '5. LukLok Casino is not liable for any computer or program malfunctions or errors in Rewards. LukLok Casino reserves the right to exclude certain Players from the Invite Friends Program, as well as the right to withhold the Reward in circumstances where LukLok Casino in its sole discretion suspects any actions related to the Invited Friend or Reward are fraudulent or LukLok Casino determines that your or the Invited Friend\'s actions are in violation of these Terms of Use or the LukLok Casino Terms of Service, including, without limitation, sharing User Account credentials with other Players, circumventing LukLok Casino\'s age, identity and/or location verification procedures, and/or abusing the Website or Platform in any way.',
      },
    ],
  },
  {
    id: 'fraud-taxes',
    title: '3. Fraud, financial crime and taxes',
    blocks: [
      {
        type: 'paragraph',
        text: '1. If we, in our sole discretion, suspect any fraud or violations of these Terms of Use or the LukLok Casino Terms of Service, LukLok Casino may, in its sole discretion, require you to return any Reward(s) or we may void, cancel, delay or withhold Rewards.',
      },
      {
        type: 'paragraph',
        text: '2. You must comply with all applicable laws, and any policy, terms, or conditions provided to you by LukLok Casino in relation to money laundering, financial crime and/or the proceeds of crime.',
      },
      {
        type: 'paragraph',
        text: '3. All taxes due in connection with any Rewards distributed to you are your sole liability. You are responsible for paying all federal, state, local, and other taxes associated with your Rewards in accordance with the laws that apply to you.',
      },
    ],
  },
  {
    id: 'ftc-compliance',
    title: '4. FTC Compliance, Marketing Activities and Responsibilities',
    blocks: [
      {
        type: 'paragraph',
        text: '1. You are solely responsible and liable for the content and manner of your referral marketing activities related to the Invite Friends Program. All such marketing activities must be professional, proper, and lawful, and must comply with all applicable laws, rules, and regulations, including, without limitation, any laws relating to the content and nature of advertising or marketing and the Endorsement and Testimonial Guidelines published by the United States Federal Trade Commission (FTC Guidelines). Your content and the manner of your referral marketing activities related to the Invite Friends Program must at all times comply with these Terms of Use. Without limiting the generality of this clause 4.1, you shall include within all pages, blogs, posts, social media posts, or other messaging where Links are posted all disclosure statements required by applicable laws, rules, and regulations, including, without limitation, the FTC Guidelines, as well as any other disclosures provided to you by LukLok Casino or required by LukLok Casino. All disclosure statements must comply with all applicable laws, rules, and regulations as well as all requirements provided or required by LukLok Casino.',
      },
      {
        type: 'paragraph',
        text: '2. You must not yourself, nor may you permit, assist, or encourage any other person to:',
      },
      {
        type: 'list',
        items: [
          'Offer directly or indirectly to any person or entity any consideration, reward, rebates, incentives, discounts, or any other benefit for using Links and completing any Required Activity. Offering such reward schemes is strictly prohibited and will be considered a breach of these Terms of Use;',
          'Take any action or make any statements that could cause any confusion as to your relationship with LukLok Casino or any other third party or as to the ownership or operation of the Website or the Platform;',
          'Register a User Account or make Gold Coin purchases on any User Account (directly or indirectly) through your Link for your own personal use and/or the use of your relatives, friends, employees, agents or advisors, or otherwise attempt to artificially increase the number of Invited Friends credited to you or Rewards payable to you, or in any other way attempt to defraud LukLok Casino;',
          'Promote, describe, or advertise LukLok Casino and/or LukLok Casino products or services as gambling or adult content, or promote or advertise, including, without limitation, posting Links, LukLok Casino and/or LukLok Casino products or services on any gambling, adult content, illegal file sharing or warez/hacker sites, or otherwise link to any gambling, adult, illegal file sharing or warez/hacker sites, including any website that contains nudity, pornography, or sexually explicit or adult-related content or materials;',
          'Represent or otherwise imply that the purpose of the Platform is anything other than personal entertainment, including a method of earning money;',
          'Represent or otherwise imply that the Platform is a real-money casino or offers real-money gambling, including describing the Platform as a casino without qualifying it as a social casino, sweepstakes casino or similar;',
          'Represent or otherwise imply that Sweepstakes Coins may be purchased or that the purchase price for Gold Coins includes the purchase price of Sweepstakes Coins;',
          'Represent or otherwise imply that you are a director, officer, employee, representative, consultant or agent of LukLok Casino or any third party Game provider, or have insider knowledge of LukLok Casino, the Game providers and/or their respective business operations;',
          'Represent or otherwise imply that Players can win real money based on gameplay on the Platform;',
          'Directly or indirectly, disparage or otherwise harm the reputation of the Platform, any part of it, the third party Game providers, LukLok Casino or their respective affiliates;',
          'Appeal specifically to children or individuals under 18 years of age;',
          'Insult, defame, offend or unlawfully discriminate against any individual or group;',
          'Infringe any person\'s rights, including intellectual property rights;',
          'Use any religious or racial themes or cultural stereotypes;',
          'Use any sexual, pornographic, extremist or otherwise offensive themes;',
          'Use terminology consistent with a real-money gambling offering, including the words "deposit", "withdrawal", "cash-out", "bet" and "wager";',
          'Implement any technique or technology that posts or serves any advertisements or promotional content around or in conjunction with the display of our websites (e.g., "framing" or pop-up windows);',
          'Use any form of unsolicited commercial e-mail (SPAM);',
          'Violate the terms of service of, or abuse, social media websites such as Facebook, Twitter, Instagram, Craigslist or any and all others in connection with your marketing activities (the term "Abuse" shall mean spamming, sending any unsolicited mass mailing or instant messaging, using social media websites for commercial purposes);',
          'Seek to purchase or register, or purchase or register, any keywords, search terms, or other identifiers that include the word "LukLok Casino" or variations thereof for use in any search engine, portal, sponsored advertising service, or other search or referral service;',
          'Promote LukLok Casino and/or our Contests in a profane, obscene, or unlawful manner, or in any manner that could reasonably be construed as damaging to LukLok Casino; or',
          'Promote any Required Activity or incentivize referrals without explicit written permission from LukLok Casino.',
        ],
      },
      {
        type: 'paragraph',
        text: '3. If we determine, in our sole discretion, that you have engaged in any of the activities described in clause 4.2 or otherwise violated these Terms of Use or the LukLok Casino Terms of Service, we may, in our sole discretion and without limiting any other rights or remedies available to us, withhold, void, or require the return of any Rewards.',
      },
    ],
  },
  {
    id: 'definitions',
    title: '5. Definitions Applicable to these Terms of Use',
    blocks: [
      {
        type: 'paragraph',
        text: '1. Words capitalized in these Terms of Use have the meanings given in the LukLok Casino Terms of Service. Words capitalized and in parentheses have the meanings given there. In addition, the following words have the following meanings in these Terms of Use:',
      },
      {
        type: 'paragraph',
        text: 'Additional Terms means any additional terms and conditions specific to your participation in the Invite Friends Program that we send to you by email to the email address registered on your User Account.',
      },
      {
        type: 'paragraph',
        text: 'LukLok Casino means the Platform available via the Website, operated by Veloraxy Interactive, Inc.',
      },
      {
        type: 'paragraph',
        text: 'Invite Friends Program Page means www.luklokcasino.com.',
      },
      {
        type: 'paragraph',
        text: 'Invited Friend means an individual that you refer to LukLok Casino via the Invite Friends Program who meets the following criteria:',
      },
      {
        type: 'list',
        items: [
          'The individual does not have any prior or existing LukLok Casino User Accounts;',
          'The individual accesses LukLok Casino directly through a Link, as defined below;',
          'The individual successfully creates a new User Account on LukLok Casino;',
          'The individual completes all Required Activity set forth on the Invite Friends Program Page at that time and/or in any additional terms specific to your participation in the Invite Friends Program; and',
          'The individual complies with these Terms of Use and the LukLok Casino Terms of Service in all respects.',
        ],
      },
      {
        type: 'paragraph',
        text: 'Link means a unique URL link provided by LukLok Casino that directs a referred person to the Website and allows LukLok Casino to track and attribute Invited Friends.',
      },
      {
        type: 'paragraph',
        text: 'Player means any individual that has a User Account on LukLok Casino.',
      },
      {
        type: 'paragraph',
        text: 'Required Activity means the required actions that are live on the Invite Friends Program Page at the time that an individual clicks on your Link, or if we provide you with Additional Terms, the required actions set forth in those Additional Terms, if any.',
      },
      {
        type: 'paragraph',
        text: 'Reward means the applicable Invite Friends Program reward that is live on the Invite Friends Program Page at the time that your Invited Friend completes the Required Activity or, if we provide you with Additional Terms, as specified in any Additional Terms specific to your participation in the Invite Friends Program.',
      },
    ],
  },
]
